### ISSUE TITLE
Rejecting secure video stream without encryption details: video 3093 RTP/SAVPF

### ISSUE THREAD

**Issue by gudge25** [versatica/JsSIP#300]
i unchecked "enable video" but  http://tryit.jssip.net/  is still trying to send video 
Thanks

**Comment by jmillan** [comment]
Hi,

This is because the `offerToReceiveVideo` option is set to true in the demo. This way, even if the caller does not offer video, it can receive if the the called is willing to do so.

`offerToReceiveVideo` is an option accepted by RTCPeerConnection for this purposes.

This is not a bug but a behaviour pre-defined in the tryit demo.

**Comment by gudge25** [comment]
can U adwice me where exactly in the code i need set this parameter to falce (there are several places)
Thanks

**Comment by jmillan** [comment]
Yes, if you don't want this behaviour you must not set the `offerToReceiveVideo` value to `true` in the `rtcOfferConstraints` optional parameter of `ua.call()`method.

http://jssip.net/documentation/0.6.x/api/ua/#method_call

Please, use the mailing list for further questions on this topic.
