### ISSUE TITLE
issue when running node server.js

### ISSUE THREAD

**Issue by descartin** [versatica/JsSIP#310]
Hello all

when trying to run the simple UA code, i get this error

/home/david/node_modules/jssip/lib/RTCSession.js:235
    throw new Exceptions.NotSupportedError('WebRTC not supported');
          ^
Error
    at Exceptions.NotSupportedError (/home/david/node_modules/jssip/lib/Exceptions.js:40:27)
    at Object.<anonymous> (/home/david/node_modules/jssip/lib/Exceptions.js:42:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/david/node_modules/jssip/lib/JsSIP.js:11:18)
    at Module._compile (module.js:456:26)

do we need to load any module or make any adjustment to the package.json or add/modify any lib .js file? seems like the server node creates doesnt support webrtc ¿?

best regards
david

**Comment by ibc** [comment]
Node does not support WebRTC (may be there is some module available, no idea).

**Comment by descartin** [comment]
just to clarify myself
in the first line of the documentation says "Runs in the browser and Node.js"
then i understand i'm trying to load the jssip in node by doing the script direclty on node or creating a httpserver on node. and i guess the webrtc is supported by the browser.
so then i understand that i have to make something like a server with express to run some html code in the browser and from there i could be able to call the jssip code?

otherwise i dont understand how i can involve node with jssip

regards

**Comment by ibc** [comment]
"Runs in Node.js" means that you can create a Node script, load JsSIP via `var JsSIP = require('jssip')`, create a UA instance, connect and register into a SIP WebSocket server/proxy, send MESSAGE requests to others, etc. You cannot make a call because Node does not implement WebRTC.

Please don't mix server side and client (browser) side. If you want to build a HTML page containing JsSIP just load jssip.js into your HTML. How you produce the HTML does not matter. Forget "JsSIP in Node".

P.S.: Please use the mailing list for questions. This is the project bug tracker.
