### ISSUE TITLE
re-INVITE contains an SDP with incorrect session identifier and version number

### ISSUE THREAD

**Issue by tilman22** [versatica/JsSIP#312]
In the o line of the SDP, the first number specifies the session identifier and the second number specifies the version number. For example, in 
o=Mozilla-SIPUA-36.0.4 11388 0 IN IP4 0.0.0.0
the 11388 is the session identifier and 0 is the version.

IS: The version is always 0 and the session identifier changes (by random?)
SHOULD: When the media is modified, then the new sdp should use the exisiting session identifer and the version should be incremented by 1.

Maybe pc.setRemoteDescription() only works (for Firefox) because the version is always 0. Not changing the version means that there is no change in the media (also no hold-related changes).

**Comment by jmillan** [comment]
Hi @tilman22,

JsSIP does not touch the SDP version at all, but respects the one generated by the browser. You can file an issue on Firefox bugtracker if you are concerned about this issue.

Lets comment it on the mailing list if necessary.

**Comment by ibc** [comment]
> Maybe pc.setRemoteDescription() only works (for Firefox) because the version is always 0. Not changing the version means that there is no change in the media (also no hold-related changes).

Not sure why you say that. SDP re-negotiation works fine between Chrome regardless the SDP version number is not increased. You are right in the sense that it should be incremented, but it should be done by the WebRTC layer (this is, the browser). JsSIP should not have to mangle the SDP to fix it.

BTW: have you experimented a re-negotation problem between Chrome (JsSIP) and any other SIP device due this issue?

**Comment by tilman22** [comment]
tryit.jssip.net is creating a new PeerConnection whenever it holds/unholds. So (for each re-INVITE) a new SDP-Session-Number is used, and the version number is always 0. No idea why tryit.jssip.net does not use the api directly.

When using jssip directly (i.e. JsSip.RTCSession.hold()/unhold()), then (for each re-INVITE) the Session-Number remains the same and the version-number increases (in my test setup, this did not work with firefox, only with chrome).

When using the same PeerConnection, then it does not seem to be possible to use a new remote fingerprint, remote ufrag/pwd etc. So creating a new PeerConnection seems to be an option.

**Comment by jmillan** [comment]
Hi,

>tryit.jssip.net is creating a new PeerConnection whenever it holds/unholds. So (for each re-INVITE) a new SDP-Session-Number is used, and the version number is always 0. No idea why tryit.jssip.net does not use the api directly.

tryit.jssip.net has a 'custom' mechanism to detect devices which don't support re-negotiations. The motivation is to support such peers. Peers using tryit.jssip.net set a custom SIP header field 'X-Can-Renegotiate' in both requests and responses containing SDP.

When it comes to re-negotations (hold/unhold/UPDATE/re-INVITE), only in case both peers support re-negotiations, based on that custom discovery mechanism, a normal re-negotiation is done, taking the offer/answer from the RTCPeerConnection normally. In case one of the peers does not support re-negotiations, again based on the custom discovery mechanism, then the RTCPeerConnection is reseted, this is, a new one is created for the call, thus a new SDP session number appears.

>When using jssip directly (i.e. JsSip.RTCSession.hold()/unhold()), then (for each re-INVITE) the Session-Number remains the same and the version-number increases (in my test setup, this did not work with firefox, only with chrome).

Because the RTCPeerConnection is done at application level (tryit.jssip.net)

>When using the same PeerConnection, then it does not seem to be possible to use a new remote fingerprint, remote ufrag/pwd etc. So creating a new PeerConnection seems to be an option.
