### ISSUE TITLE
No video after hangup while on hold when passing media stream to JsSIP

### ISSUE THREAD

**Issue by pg94au** [versatica/JsSIP#338]
When a call is placed, put on hold, and then hung up (or the connection is otherwise terminated) while on hold, the next call established with the same streams will contain audio but no video.  Putting that call on hold and then unholding it brings back the video stream on the call.

**Comment by ibc** [comment]
Since 0.7.8 there is a new [RTCSession#resetLocalMedia()](http://jssip.net/documentation/0.7.x/api/session/#method_resetLocalMedia) method that resets the local MediaStream tracks by enabling them (unless the remote peer is on hold).

You can call it within your new session to avoid the issue described above.
