### ISSUE TITLE
Ended event not firing when remote party terminates the call

### ISSUE THREAD

**Issue by joshfarrant** [versatica/JsSIP#361]
I'm trying set up an event handler to fire when the remote party terminates the call and a BYE is received, which I believe should be the _ended_ event, however it isn't firing. The event does fire when the client ends the call, as I would expect.

As far as I can tell from the [documentation](http://jssip.net/documentation/0.7.x/api/session/#event_ended) (and from the [JsSIP demo](https://tryit.jssip.net/)) the _ended_ event is the correct event to hook in to to detect when the call is terminated from either end.

Is this expected behaviour, or am I looking in the wrong place?

**Comment by ibc** [comment]
Of course "ended" will fire. No doubts here, it just works, sure.

Enable full debug to see what happens when the BYE is received, it may be a SIP parsing error or whatever, and ensure that your JsSIP replies 200 to the incoming BYE.

NOTE: This is not a bug. If you have further questions please use the mailing list.

**Comment by joshfarrant** [comment]
Great, cheers for the fast response, will double check that and try the mailing list as a next step.
