### ISSUE TITLE
Call failures on Chrome 52

### ISSUE THREAD

**Issue by chadwallacehart** [versatica/JsSIP#378]
I am using the Chrome Beta Channel and starting having issues with Voxbone's WebRTC service (they use JsSIP v0.7.9). Calls on Chrome 52 disconnect immediately. To validate it was not something specific to the Voxbone WebRTC service, I tried it at https://tryit.jssip.net/.

Steps to reproduce:
1. Go to https://tryit.jssip.net/ and "use dynamic account"
2. Click on the "invite others to call you" link
3. type  chat message to validate connectivity
4. try calling
5. go to the other answer to receive the call

Then you hear a strange buzzing for about half of a second and the call disconnects. I see a "SIP/2.0 408 Request Timeout" in the console logs.

This is the view from the receiver tab:
![image](https://cloud.githubusercontent.com/assets/6531125/15876727/21ac1508-2cdd-11e6-8214-cf67d53c3bfb.png)

It works fine when I use Chrome 50 on my Mobile.

I asked others to test Voxbone's services with different versions of Chrome. It works up to Chrome 51, but fails on Chrome 52 and 53.

You can test Voxbone's site by going to https://www.voxbone.com/ and scrolling down to the bottom where you will see a purple "click-to-call" button.

**Comment by san983** [comment]
Same issue here

**Comment by jmillan** [comment]
Tested (https://tryit.jssip.net/) in Chrome version 52.0.2743.19 dev (64-bit), I'm not getting any issue.

By the way, JsSIP is already in version 2.0.0.

Please, test https://tryit.jssip.net/ and paste here the browser console log of the failing tab.

**Comment by ibc** [comment]
Please, as said multiple times, don't report issues regarding the Tryit demo app. If you find a real bug in JsSIP (something you can document more than "it fails with your demo app") please report it here. Otherwise let's assume that Tryit demo is just a demo app running in a server that may experiment network issues or whatever at any time.

SIP 408 response means that, somehow, the INVITE did not reach the remote endpoint so our proxy in the middle (OverSIP) replied 408. It may be due to a temporal network failure or whatever, but we cannot give support regarding the Tryit demo app.

Said that, it works for me (right now) in Chrome Canary (53).

**Comment by chadwallacehart** [comment]
Sorry, my bad. This was an ECSDA DTLS handshake issue at Voxbone. I guess I just got unlucky with my connection to tryip.jssip.net. We won't use that as a reference in the future.
