### ISSUE TITLE
Not negotiating Session Expire

### ISSUE THREAD

**Issue by hitokiri82** [versatica/JsSIP#397]
Hello. 

I'm trying to use the demo app to try out your library. The calls fail because in the SIP INVITE the Session-Expires is set to 90 and my SIP server (Freeswitch) is rejecting the call with a SIP 422 Message (Session Interval Too Small) and a Min-SE header of 120 after which JsSIP responds with an ACK. 

I would guess that the proper action in this case would be to send the INVITE again but with the proper Session-Expires value but I'm not sure. 

Would you say this is a bug, or just the way JsSIP works? 

Is there any way to adjust this parameter?

**Comment by jmillan** [comment]
Hi,

Check the related documentation:

http://jssip.net/documentation/2.0.x/api/ua_configuration_parameters/#parameter_session_timers
http://jssip.net/documentation/2.0.x/api/ua/#method_call (sessionTimersExpires option)

Closing since this is not an issue. Please use the mailing list for JsSIP questions.
