### ISSUE TITLE
Firefox take about 10sec to give audio

### ISSUE THREAD

**Issue by Atomico001** [versatica/JsSIP#565]
I don't know why but with firefox when a call is done i need to wait about 10 second before audio show up in both direction, while with chrome is instant.

**Comment by davies147** [comment]
This is not a JsSIP bug, it is a browser issue.

It is probably because Chrome has clever code to not try and get ICE candidates from down or useless network interfaces, I do not think Firefox is quite that clever.

If you trace the ice candidates and when ice-complete happens in each browser you should see what I mean (assuming I am correct ;) ).

**Comment by Atomico001** [comment]
Thanks for answer, can you explain me what are the ICE candidates?

**Comment by jmillan** [comment]
Please, use the mailing list :-)
