### ISSUE TITLE
Semi-Attended Transfer on ring

### ISSUE THREAD

**Issue by michelepra** [versatica/JsSIP#566]
I try to manage this situation

1. A call B
2. B answer  (call1)
3. B hold A
3. B dial C (call2)
3. B on RTCSession progress event (180 ringing) refer call2 to call1

jssip not send refer and reporting error on this function

```javascript
  sendRequest(method, options)
  {
    this.debug('sendRequest()');

    return this._dialog.sendRequest(method, options);
  }
```
because this._dialog === undefined.

**Comment by jmillan** [comment]
[Semi-Attended Transfer](https://tools.ietf.org/html/rfc5589#section-7.6) is a **PBX** feature intended to transfer a call even when the Transferor hangs up before the second party answers the call, but the `REFER` SIP message is sent once the dialog is confirmed and not in an early state.

In you patch you are creating a confirmed dialog upon **180** and **183** responses just for your convenience. Apart from being incorrect that would lead into issues when receiving such responses from different endpoints due to parallel forking.

Please use the blind or the attended transfer features which are the ones available at endpoint level.
