### ISSUE TITLE
Case sensitive string compare for SIP Username

### ISSUE THREAD

**Issue by BlueCall** [versatica/JsSIP#614]
"Normally" user name or server name should not be case sensitive.
At least the SIP user name seems be be case sensitive.
For ex. the user name Sam is not found by JsSIP when sam is logged on. This is not a practicable user experience.

Is there any config to make JsSIP case insensitive ?
Can a contributer code case insensitivity for user name / server name in JsSIP ?

**Comment by ibc** [comment]
Please, use the JsSIP mailing list for questions (as the issue templete that you have ignored clearly says).

And no, SIP URI username is case sensitive. The RFC is clear about this, so this is not gonna change because it's ok. Fix your server side to be RFC 3261 compliant. Please use the mailing list for further questions.
