### ISSUE TITLE
Possibility of WebRTC in Node with a new parameter passed to UA?

### ISSUE THREAD

**Issue by hieyou1** [versatica/JsSIP#723]
Thanks for taking a look at this. I know that #349, #415, #403, and #310 are all this same thing, but they were also all closed a number of years ago. Now, with great libraries like [node-webrtc](https://github.com/node-webrtc/node-webrtc#readme), which, according to its README, "is a Node.js Native Addon that provides bindings to WebRTC", it is now possible to use WebRTC in Node.

However, it is still not supported by this library. I would really appreciate this feature.

My suggestion for how to implement this is to use a new parameter in JsSIP.UA() called "wrtc" [or something similar], as [simple-peer already does](https://github.com/feross/simple-peer#in-node). This parameter would be optional, and if left undefined, would default to the "window.*" APIs.

I'm still unsure if solving #427 would solve this problem.

**Comment by ibc** [comment]
We won't do that because if we did that we would automatically become responsible of what such a library that we don't know (node-webrtc) behaves, and from my past experience it does not behave well at all.

So instead of that, we are gonna remove WebRTC entirely from JsSIP and make the app responsible of it.

BTW please use the mailing list for questions or suggestions.
