### ISSUE TITLE
Vue3 + jsSIP cannot be used properly

### ISSUE THREAD

**Issue by vssir** [versatica/JsSIP#782]
Hello everyone, I found a problem, the project is based on VUE3 + TS + Vite, the following error occurs when SIP users register after compiling.

Is it a BUG?

console err:
![image](https://user-images.githubusercontent.com/10388068/181239697-c9a9b79f-8781-4630-aa46-17848a098f58.png)

position:
![image](https://user-images.githubusercontent.com/10388068/181239802-76629a35-3f75-42ff-92ca-ba5cb57b5d7b.png)

jssip source code:
![image](https://user-images.githubusercontent.com/10388068/181240249-02a83610-9d63-4c62-9d23-b5e307100aa9.png)

**Comment by boren4321** [comment]
hi, how to resole it?pls

**Comment by antant7** [comment]
The issue persists - Quasar (Vue3) + TS + Vite - only after project build. No errors in dev mode.

Temporary workaround - modify line **\node_modules\jssip\lib-es5\NameAddrHeader.js:37** 
from ```if (!uri || !(uri instanceof URI))``` to ```if (!uri || (URI && !(uri instanceof URI)))```.

After updating the package, you'll need to re-edit it again. It's very inconvenient, but otherwise SIP calls stop working.

**Comment by shevtsov-max** [comment]
My [pull request](https://github.com/versatica/JsSIP/pull/889) for a change was rejected, so I had to create a "forker" in my profile in order to use the library.

edit package.json
`"jssip": "https://github.com/shevtsov-max/JsSIP/tarball/master",`

It helped me.
