### ISSUE TITLE
socket: WebSocketInterface, error: true, code: 1006, reason: ''当频繁刷新去连接信令服务时，收到一个新的来电，去接听这个通话，而此时信令服务正好断开，导致无法正常接听，如何规避这个问题呢？

### ISSUE THREAD

**Issue by ycl-hub** [versatica/JsSIP#816]
![e2cbbbce4dca3054c158d47493706ad](https://github.com/versatica/JsSIP/assets/74390814/6498a16a-1b5f-4dd8-83a0-88d70e265716)

**Comment by ycl-hub** [comment]
当频繁刷新浏览器去重新连接信令服务器时，收到来电通话，这个时候接听经常会遇到服务断开的情况，导致无法正常去answer接听通话

**Comment by lixuanqun** [comment]
与信令服务断开，则后续接听、拒接等操作均会受到影响。
1 建议不要频繁去刷新链接信令服务。
2 websocket链接本身需要 设置保活机制，即定时的发ping心跳
3 在少数情况下，如果websocket确实断了。此时接到新来电，是无法正常相应的，也无需正常相应。因为我们是无法确定当前浏览器终端是否还正常工作，或者当前网络是否还正常。
-----------------------------------------------------
If disconnected from signaling services, subsequent operations such as answering and rejecting will be affected.
1. It is recommended not to frequently refresh the link signaling service.
The websocket link itself needs to set a keep alive mechanism, which means sending ping heartbeats at regular intervals
In rare cases, if the websocket does indeed break. At this time, receiving a new call cannot be responded to normally, and there is no need to respond normally. Because we cannot determine whether the current browser terminal is still working properly or whether the current network is still functioning properly.
