### ISSUE TITLE
Allow INVITE without SDP

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#91]
Allow receiving an INVITE without SDP and then generate the SDP offer in the 200 by asking the app/user which kind of media to offer.

**Comment by soulofmischief87** [comment]
Was support for this ever added? I am using the latest lib JsSIP 0.7.9 and I am seeing a response with video and audio in the 200 ok SDP. But the browser isn't prompting for permission and therefore not sending neither audio or video to the UAC. Please advise.

**Comment by ibc** [comment]
>  I am seeing a response with video and audio in the 200 ok SDP.

What do you mean? In which case do you see such a 200 response?

**Comment by soulofmischief87** [comment]
When sending an invite without sdp to a JSSIP client (acting as UAS in the call flow)and subsequently answering a call via the answer method without passing any options  . The user isn't prompted for permission to access the devices via the browser it will just generate a 200 ok with SDP with video and audio params consequently doesn't send video or audio since the devices aren't accessed.
